build:
  version: 2016-03-14
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile.builder
      artifacts:
        - /app/janitor
    executor:
      name: executor
      dockerfile: Dockerfile.executor
      depends_on:
        - builder
