#use the alpine base image
FROM alpine:3.4
MAINTAINER Vic van Gool

RUN mkdir -p /etc/ssl/certs/
RUN apk add --update ca-certificates
RUN update-ca-certificates --fresh

#switch to our app directory
RUN mkdir -p /app
WORKDIR /app

#copy the binary
ADD ./janitor /app
RUN chown daemon:daemon /app/janitor && chmod 700 /app/janitor

USER daemon
